import type { PixelAgentData } from './PixelCharacter';

// Floor 1: Análisis e Investigación — agentes de búsqueda y datos
export const floor1Agents: PixelAgentData[] = [
  {
    id: 'vizta-search',
    name: 'Vizta',
    role: 'Agente Principal',
    specialty: 'vizta',
    greeting: '¡Hola! Soy Vizta, tu agente de investigación con IA. Puedo buscar noticias, tendencias, analizar información y mucho más. ¿Qué necesitas investigar?',
    color: 'hsl(210, 70%, 65%)',
    hairColor: 'hsl(220, 60%, 20%)',
    shirtColor: 'hsl(250, 60%, 45%)',
    startX: 45, startY: 45,
    minX: 30, maxX: 60, minY: 30, maxY: 65,
    speed: 0.2,
    viztaContext: 'Eres el agente Vizta principal. Responde con información precisa y actualizada.',
  },
  {
    id: 'trending-agent',
    name: 'Tren',
    role: 'Analista de Tendencias',
    specialty: 'trending',
    greeting: '¡Hey! Soy Tren, el especialista en tendencias. Dime un tema y te digo qué está pasando en redes sociales y medios ahora mismo.',
    color: 'hsl(30, 50%, 68%)',
    hairColor: 'hsl(0, 70%, 25%)',
    shirtColor: 'hsl(15, 70%, 45%)',
    startX: 20, startY: 50,
    minX: 10, maxX: 35, minY: 35, maxY: 68,
    speed: 0.25,
    viztaContext: 'Enfócate en tendencias trending, redes sociales y buzz mediático.',
  },
  {
    id: 'news-agent',
    name: 'Nova',
    role: 'Buscadora de Noticias',
    specialty: 'news',
    greeting: '¡Hola! Soy Nova, especialista en noticias. Si hay algo importante pasando en Guatemala o el mundo, yo lo encuentro. ¿Qué quieres saber?',
    color: 'hsl(32, 52%, 65%)',
    hairColor: 'hsl(20, 80%, 15%)',
    shirtColor: 'hsl(160, 50%, 38%)',
    startX: 72, startY: 48,
    minX: 58, maxX: 85, minY: 32, maxY: 68,
    speed: 0.28,
    viztaContext: 'Enfócate en noticias recientes, eventos actuales y periodismo.',
  },
];

// Floor 2: Investigación Digital — agentes especializados
export const floor2Agents: PixelAgentData[] = [
  {
    id: 'data-agent',
    name: 'Datos',
    role: 'Analista de Datos',
    specialty: 'data',
    greeting: '¡Hola! Soy el agente de datos. Dame un tema y lo analizaré con cifras, estadísticas y patrones. ¿Qué investigamos?',
    color: 'hsl(30, 55%, 70%)',
    hairColor: 'hsl(200, 60%, 20%)',
    shirtColor: 'hsl(210, 60%, 48%)',
    startX: 18, startY: 42,
    minX: 8, maxX: 32, minY: 30, maxY: 62,
    speed: 0.18,
    viztaContext: 'Enfócate en análisis de datos, estadísticas y patrones cuantitativos.',
  },
  {
    id: 'digital-agent',
    name: 'Cyber',
    role: 'Investigador Digital',
    specialty: 'digital',
    greeting: '¡Hey! Soy Cyber, investigador digital. Redes sociales, metadatos, huella digital... lo digital es mi territorio. ¿Qué rastreamos?',
    color: 'hsl(35, 48%, 68%)',
    hairColor: 'hsl(0, 70%, 30%)',
    shirtColor: 'hsl(170, 50%, 38%)',
    startX: 45, startY: 52,
    minX: 33, maxX: 58, minY: 35, maxY: 68,
    speed: 0.15,
    viztaContext: 'Enfócate en investigación digital, redes sociales y análisis de contenido online.',
  },
  {
    id: 'search-agent',
    name: 'Scout',
    role: 'Buscador Web',
    specialty: 'search',
    greeting: '¡Hola! Soy Scout, especialista en búsqueda. Puedo encontrar información de múltiples fuentes web sobre cualquier tema. ¿Qué buscamos?',
    color: 'hsl(28, 50%, 62%)',
    hairColor: 'hsl(280, 50%, 28%)',
    shirtColor: 'hsl(45, 70%, 48%)',
    startX: 72, startY: 45,
    minX: 60, maxX: 85, minY: 30, maxY: 62,
    speed: 0.22,
    viztaContext: 'Enfócate en búsqueda web, síntesis de múltiples fuentes y descubrimiento de información.',
  },
];

// Floor 3: Dirección — estrategia y memoria
export const floor3Agents: PixelAgentData[] = [
  {
    id: 'strategy-agent',
    name: 'Rex',
    role: 'Director Estratégico',
    specialty: 'strategy',
    greeting: 'Soy Rex, director de investigaciones. Si necesitas una estrategia completa de investigación, análisis en profundidad o coordinar múltiples temas, habla conmigo.',
    color: 'hsl(30, 40%, 58%)',
    hairColor: 'hsl(0, 0%, 58%)',
    shirtColor: 'hsl(0, 0%, 22%)',
    startX: 28, startY: 44,
    minX: 15, maxX: 42, minY: 30, maxY: 62,
    speed: 0.1,
    viztaContext: 'Proporciona análisis estratégico profundo, perspectiva amplia y síntesis compleja de múltiples fuentes.',
  },
  {
    id: 'archive-agent',
    name: 'Memo',
    role: 'Archivista IA',
    specialty: 'archives',
    greeting: 'Soy Memo, el archivista de contexto. Tengo acceso al historial de investigaciones y al Codex. Si algo pasó antes, yo lo recuerdo. ¿Qué buscas en el pasado?',
    color: 'hsl(28, 45%, 64%)',
    hairColor: 'hsl(30, 30%, 52%)',
    shirtColor: 'hsl(330, 40%, 42%)',
    startX: 62, startY: 50,
    minX: 48, maxX: 75, minY: 33, maxY: 65,
    speed: 0.12,
    viztaContext: 'Enfócate en contexto histórico, información previa del Codex y conexiones entre eventos pasados y presentes.',
  },
];

export const allPixelAgents = [...floor1Agents, ...floor2Agents, ...floor3Agents];

export const floorConfigs = [
  {
    floorNumber: 1,
    label: 'P1 — Central de Agentes',
    wallColor: 'hsl(32, 30%, 82%)',
    floorColor: 'hsl(30, 12%, 68%)',
    floorType: 'tile' as const,
    agents: floor1Agents,
  },
  {
    floorNumber: 2,
    label: 'P2 — Investigación Digital',
    wallColor: 'hsl(30, 35%, 78%)',
    floorColor: 'hsl(28, 32%, 48%)',
    floorType: 'wood' as const,
    agents: floor2Agents,
  },
  {
    floorNumber: 3,
    label: 'P3 — Dirección Estratégica',
    wallColor: 'hsl(35, 38%, 80%)',
    floorColor: 'hsl(340, 22%, 40%)',
    floorType: 'carpet' as const,
    agents: floor3Agents,
  },
];
